require 'ci/reporter/rake/rspec'
task :rspec => 'ci:setup:rspec'

require 'rake'
require 'rspec/core/rake_task'

#RSpec::Core::RakeTask.new(:spec) 
RSpec::Core::RakeTask.new(:integration_tests) 

#task :default => :integration_tests


