require 'rest-client'
require 'json'
require 'uri'

require File.dirname(__FILE__) + '/lib/Client'
require File.dirname(__FILE__) + '/lib/AuthClient'
require File.dirname(__FILE__) + '/lib/Authenticator'
require File.dirname(__FILE__) + '/lib/JsonPayloadReader'
require File.dirname(__FILE__) + '/lib/JsonPayloadWriter'
require File.dirname(__FILE__) + '/lib/Requester'
require File.dirname(__FILE__) + '/lib/BaseResource'
require File.dirname(__FILE__) + '/lib/AttachmentResource'
require File.dirname(__FILE__) + '/lib/AccessTokenResource'
require File.dirname(__FILE__) + '/lib/ChannelResource'
require File.dirname(__FILE__) + '/lib/ContactAddressHistoryResource'
require File.dirname(__FILE__) + '/lib/ContactAddressStatusResource'
require File.dirname(__FILE__) + '/lib/ContactExportResource'
require File.dirname(__FILE__) + '/lib/ContactFastAccessResource'
require File.dirname(__FILE__) + '/lib/ContactFastAccessJobResource'
require File.dirname(__FILE__) + '/lib/ContactGroupResource'
require File.dirname(__FILE__) + '/lib/ContactImportResource'
require File.dirname(__FILE__) + '/lib/ContactResource'
require File.dirname(__FILE__) + '/lib/ContactAccessTokenResource'
require File.dirname(__FILE__) + '/lib/ContactApplicationTokenResource'
require File.dirname(__FILE__) + '/lib/KeywordResource'
require File.dirname(__FILE__) + '/lib/MessageRequestResource'
require File.dirname(__FILE__) + '/lib/MessageResource'
require File.dirname(__FILE__) + '/lib/MessageTemplateResource'
require File.dirname(__FILE__) + '/lib/SenderIdClassResource'
require File.dirname(__FILE__) + '/lib/SenderIdResource'
require File.dirname(__FILE__) + '/lib/SenderIdTypeResource'
require File.dirname(__FILE__) + '/lib/StatisticsResource'
require File.dirname(__FILE__) + '/lib/Factory'
